//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aphrodite.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class FormSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FormSettings defaultInstance = ((FormSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FormSettings())));
        
        public static FormSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32000, -32000")]
        public global::System.Drawing.Point frmMain_Location {
            get {
                return ((global::System.Drawing.Point)(this["frmMain_Location"]));
            }
            set {
                this["frmMain_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32000, -32000")]
        public global::System.Drawing.Point frmBlacklist_Location {
            get {
                return ((global::System.Drawing.Point)(this["frmBlacklist_Location"]));
            }
            set {
                this["frmBlacklist_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32000, -32000")]
        public global::System.Drawing.Point frmImageDownloader_Location {
            get {
                return ((global::System.Drawing.Point)(this["frmImageDownloader_Location"]));
            }
            set {
                this["frmImageDownloader_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32000, -32000")]
        public global::System.Drawing.Point frmLog_Location {
            get {
                return ((global::System.Drawing.Point)(this["frmLog_Location"]));
            }
            set {
                this["frmLog_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32000, -32000")]
        public global::System.Drawing.Size frmLog_Size {
            get {
                return ((global::System.Drawing.Size)(this["frmLog_Size"]));
            }
            set {
                this["frmLog_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32000, -32000")]
        public global::System.Drawing.Point frmPoolDownloader_Location {
            get {
                return ((global::System.Drawing.Point)(this["frmPoolDownloader_Location"]));
            }
            set {
                this["frmPoolDownloader_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32000, -32000")]
        public global::System.Drawing.Point frmPoolWishlist_Location {
            get {
                return ((global::System.Drawing.Point)(this["frmPoolWishlist_Location"]));
            }
            set {
                this["frmPoolWishlist_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32000, -32000")]
        public global::System.Drawing.Point frmRedownloader_Location {
            get {
                return ((global::System.Drawing.Point)(this["frmRedownloader_Location"]));
            }
            set {
                this["frmRedownloader_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32000, -32000")]
        public global::System.Drawing.Point frmSettings_Location {
            get {
                return ((global::System.Drawing.Point)(this["frmSettings_Location"]));
            }
            set {
                this["frmSettings_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32000, -32000")]
        public global::System.Drawing.Point frmTagDownloader_Location {
            get {
                return ((global::System.Drawing.Point)(this["frmTagDownloader_Location"]));
            }
            set {
                this["frmTagDownloader_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32000, -32000")]
        public global::System.Drawing.Point frmUndesiredTags_Location {
            get {
                return ((global::System.Drawing.Point)(this["frmUndesiredTags_Location"]));
            }
            set {
                this["frmUndesiredTags_Location"] = value;
            }
        }
    }
}
