//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aphrodite.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class InkBunny : global::System.Configuration.ApplicationSettingsBase {
        
        private static InkBunny defaultInstance = ((InkBunny)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InkBunny())));
        
        public static InkBunny Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReadWarning {
            get {
                return ((bool)(this["ReadWarning"]));
            }
            set {
                this["ReadWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SessionID {
            get {
                return ((string)(this["SessionID"]));
            }
            set {
                this["SessionID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GuestPriority {
            get {
                return ((bool)(this["GuestPriority"]));
            }
            set {
                this["GuestPriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuestSessionID {
            get {
                return ((string)(this["GuestSessionID"]));
            }
            set {
                this["GuestSessionID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GuestGeneral {
            get {
                return ((bool)(this["GuestGeneral"]));
            }
            set {
                this["GuestGeneral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GuestMatureNudity {
            get {
                return ((bool)(this["GuestMatureNudity"]));
            }
            set {
                this["GuestMatureNudity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GuestMatureViolence {
            get {
                return ((bool)(this["GuestMatureViolence"]));
            }
            set {
                this["GuestMatureViolence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GuestAdultSexualThemes {
            get {
                return ((bool)(this["GuestAdultSexualThemes"]));
            }
            set {
                this["GuestAdultSexualThemes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GuestAdultStrongViolence {
            get {
                return ((bool)(this["GuestAdultStrongViolence"]));
            }
            set {
                this["GuestAdultStrongViolence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoggedInUsername {
            get {
                return ((string)(this["LoggedInUsername"]));
            }
            set {
                this["LoggedInUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General {
            get {
                return ((bool)(this["General"]));
            }
            set {
                this["General"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MatureNudity {
            get {
                return ((bool)(this["MatureNudity"]));
            }
            set {
                this["MatureNudity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MatureViolence {
            get {
                return ((bool)(this["MatureViolence"]));
            }
            set {
                this["MatureViolence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AdultSexualThemes {
            get {
                return ((bool)(this["AdultSexualThemes"]));
            }
            set {
                this["AdultSexualThemes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AdultStrongViolence {
            get {
                return ((bool)(this["AdultStrongViolence"]));
            }
            set {
                this["AdultStrongViolence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PicturePinup {
            get {
                return ((bool)(this["PicturePinup"]));
            }
            set {
                this["PicturePinup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sketch {
            get {
                return ((bool)(this["Sketch"]));
            }
            set {
                this["Sketch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PictureSeries {
            get {
                return ((bool)(this["PictureSeries"]));
            }
            set {
                this["PictureSeries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Comic {
            get {
                return ((bool)(this["Comic"]));
            }
            set {
                this["Comic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Portfolio {
            get {
                return ((bool)(this["Portfolio"]));
            }
            set {
                this["Portfolio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FlashAnimation {
            get {
                return ((bool)(this["FlashAnimation"]));
            }
            set {
                this["FlashAnimation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FlashInteractive {
            get {
                return ((bool)(this["FlashInteractive"]));
            }
            set {
                this["FlashInteractive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VideoAnimation {
            get {
                return ((bool)(this["VideoAnimation"]));
            }
            set {
                this["VideoAnimation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MusicSingleTrack {
            get {
                return ((bool)(this["MusicSingleTrack"]));
            }
            set {
                this["MusicSingleTrack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MusicAlbum {
            get {
                return ((bool)(this["MusicAlbum"]));
            }
            set {
                this["MusicAlbum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VideoFeatureLength {
            get {
                return ((bool)(this["VideoFeatureLength"]));
            }
            set {
                this["VideoFeatureLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WritingDocument {
            get {
                return ((bool)(this["WritingDocument"]));
            }
            set {
                this["WritingDocument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CharacterSheet {
            get {
                return ((bool)(this["CharacterSheet"]));
            }
            set {
                this["CharacterSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Photography {
            get {
                return ((bool)(this["Photography"]));
            }
            set {
                this["Photography"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SeparateMultiPosts {
            get {
                return ((bool)(this["SeparateMultiPosts"]));
            }
            set {
                this["SeparateMultiPosts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%id%")]
        public string FileNameSchema {
            get {
                return ((string)(this["FileNameSchema"]));
            }
            set {
                this["FileNameSchema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%id%_%multipostindex%")]
        public string FileNameSchemaMultiPost {
            get {
                return ((string)(this["FileNameSchemaMultiPost"]));
            }
            set {
                this["FileNameSchemaMultiPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DownloadGraylistedSubmissions {
            get {
                return ((bool)(this["DownloadGraylistedSubmissions"]));
            }
            set {
                this["DownloadGraylistedSubmissions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DownloadBlacklistedSubmissions {
            get {
                return ((bool)(this["DownloadBlacklistedSubmissions"]));
            }
            set {
                this["DownloadBlacklistedSubmissions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SeparateNonImages {
            get {
                return ((bool)(this["SeparateNonImages"]));
            }
            set {
                this["SeparateNonImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ImageLimit {
            get {
                return ((int)(this["ImageLimit"]));
            }
            set {
                this["ImageLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PageLimit {
            get {
                return ((int)(this["PageLimit"]));
            }
            set {
                this["PageLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchInKeywords {
            get {
                return ((bool)(this["SearchInKeywords"]));
            }
            set {
                this["SearchInKeywords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInTitle {
            get {
                return ((bool)(this["SearchInTitle"]));
            }
            set {
                this["SearchInTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInDescriptionOrStory {
            get {
                return ((bool)(this["SearchInDescriptionOrStory"]));
            }
            set {
                this["SearchInDescriptionOrStory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInMd5Hash {
            get {
                return ((bool)(this["SearchInMd5Hash"]));
            }
            set {
                this["SearchInMd5Hash"] = value;
            }
        }
    }
}
